networks:
  cosmos-kptv-default:
    external: true
    name: "cosmos-kptv-default"
  cosmos-kptv-internal:
    external: true
    name: "cosmos-kptv-internal"

services:
  distrotv:  # change the name

    command:
      - "python3"
      - "app.py"

    container_name: "distrotv"  # change the name

# choose one provider to separate
    environment:
      - "ENABLED_PROVIDERS=distrotv"
      - "CACHE_DURATION=7200"
      - "MAX_WORKERS=5"
      - "DEBUG=false"
      - "WARM_CACHE_ON_STARTUP=true"
      - "WARM_EPG_ON_STARTUP=true"
      - "STARTUP_CACHE_DELAY=10"
      - "PROVIDER_TIMEOUT=45"

    hostname: "distrotv"  # change it to provider

    image: "ghcr.io/kpirnie/kptv-fast:latest"

    labels:
      cosmos-force-network-mode: "cosmos-kptv-internal" # test out if to use cosmos-kptv-internal or cosmos-kptv-default
#      cosmos-stack-main: "" # true or false
      cosmos-stack: "kptv-fast" # name of the service

    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

    networks:
      - "cosmos-kptv-default"
      - "cosmos-kptv-internal"

    ports:
      - ":7777/tcp"

    restart: "unless-stopped"

    user: "appuser"
