services:
  kptv_fast:
    image: ghcr.io/kpirnie/kptv_fast:latest
    container_name: kptv_fast
    hostname: kptv_fast
    ports:
      - 7777:7777
    environment: 
    
      # Server configuration
      - PORT=7777
      - CACHE_DURATION=7200 # 2 hour

      # Startup cache warming
      - WARM_CACHE_ON_STARTUP=true    # Enable startup cache warming
      - STARTUP_CACHE_DELAY=10        # Wait 10s before warming cache
      - WARM_EPG_ON_STARTUP=false     # Also warm EPG cache (slower)
      
      # Performance
      - MAX_WORKERS=5           # Concurrent provider fetches (default: 5)
      - PROVIDER_TIMEOUT=45     # Per-provider timeout in seconds (default: 45)

      # Provider configuration: all or any of these: xumo,tubi,pluto,plex,samsung (accepts comma-delimited list)
      - ENABLED_PROVIDERS=all
      
      # Regional settings
      - PLUTO_REGION=us_east # 
      - PLEX_REGION=local # 
      - SAMSUNG_REGION=us # 
      
      # Filtering (regex patterns)
      - CHANNEL_NAME_INCLUDE= # to include streams with the names in your regex
      - CHANNEL_NAME_EXCLUDE= # to exclude streams with the names in your regex
      - GROUP_INCLUDE= # to include streams with the groups in your regex
      - GROUP_EXCLUDE= # to exclude streams with the groups in your regex

      # Debug logging
      - DEBUG=false
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7777/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s